language: python
python:
  - "3.6"
  - "3.7-dev"

# command to install dependencies
before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg

install: "make"

script:
  - make lint
  - make test

notifications:
    email: false
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MHVtaSUzQW90b25va2l6YWthLmlzLWEtbGludXgtdXNlci5vcmcvJTIxWGtYcEN5UG55RVVUTmJMeEV2JTNBbWF0cml4Lm9yZw"
        on_success: always # always|never|change
        on_failure: always
        on_start: never